### ISSUE TITLE
Do not support crypto trading right?

### ISSUE THREAD

**Issue by AlexiaChen** [virattt/ai-hedge-fund#15]
only stock market.... do not consider crypto market in the future?

**Comment by denizgedik** [comment]
Thanks for telling him he shouldn't consider crypto since it's unreliable to trade crypto even with an experienced hedge fund

**Comment by Sadmansamee** [comment]
would appreciate crypto as well

**Comment by virattt** [comment]
The current code does not support crypto.  But we can add it in the future 👍

**Comment by Mlian-m** [comment]
Has anyone created a crypto fork for your project?
Or have you already implemented it?
