### ISSUE TITLE
Suggestion: Add yfinance as Alternative Data Source 

### ISSUE THREAD

**Issue by amaboh** [virattt/ai-hedge-fund#24]
Hi and thanks for creating this educational project. 

## context
While exploring this project, I encounter API limits with the financial Dataset API (which is understandable for the free tier). Thus, this let me to thinking  of ways to experiment and learn.

## Suggestion
I'd like to propose adding yfinance as an optional/alternative data source, for Local testing and education.

I believe it would lower barriers to new contributors, enable developers to test changes locally without API limits, and also help users learn the system before upgrading to Financial Dataset API.

## Implementation Approach
The integration could be done in a way that:
1. Keeps Financial Datasets API as the default/recommended source
2. Clearly documents the limitations of yfinance compared to Financial Datasets API
3. Uses a simple configuration flag to switch between sources

Would love to hear your thoughts on this suggestion.

**Comment by virattt** [comment]
Hi @amaboh 

I'd recommend forking the repo and adding your preferred provider to your forked repository.

I am using Financial Datasets as I am the creator of the API and trust the data quality.

Also, I am building out the API while building out the AI hedge fund.
