### ISSUE TITLE
Compatibility with Openai compatible api

### ISSUE THREAD

**Issue by toolazyhhh** [virattt/ai-hedge-fund#3]
Hi! I am just wondering if the set up supports openai compatible api? If so, what adjustment do I need to make? Thanks!

**Comment by virattt** [comment]
Hey @toolazyhhh - not sure I follow the question.

The project uses OpenAI's APIs under the hood

**Comment by toolazyhhh** [comment]
Sorry for the confusion in the language. I am wondering if we can use other llm like deepseeks, groq that have an OpenAI compatible api schema. They usually cost much less than OpenAi's api(Sometimes actually for free).

**Comment by MauricioFabian** [comment]
You only need to add the following when creating the ChatOpenAI class:

`llm = ChatOpenAI(
    model="<modelname>",
    openai_api_key="<apikey>",
    base_url="<url>"
)`

**Comment by toolazyhhh** [comment]
Thanks!
