### ISSUE TITLE
A docker image for this project?

### ISSUE THREAD

**Issue by YanzhongSu** [virattt/ai-hedge-fund#9]
Hi, do you by any chance have a docker image for this project? I previously was traumatised by the experience of installing packages onto my local machine which messed up other dependencies.

**Comment by virattt** [comment]
I can add docker to this project.  Also, if you want it earlier, then please feel free to put up a pull request that adds docker support :)

**Comment by charlesvien** [comment]
@virattt https://github.com/virattt/ai-hedge-fund/pull/11

**Comment by accforgithubtest** [comment]
I am looking forward to this PR #11  getting merged.

I hope a few related things to be added as well to make this easy to use -

1. An official docker image on ghcr / dockerhub (so end users dont have to build the project)
1.  Pls add examples on how to use via docker compose to the readme files.
1. Would be good to know what are the minimum system requirements to run this. My understanding is that there are no local LLM's involved, and this project is managing the workflows between the datasource (financial dataset) and the LLM (open ai). So I assume this should be runnable reasonably well on a laptop, but would be good to know what the project's hardware minimum recommendations are.

**Comment by virattt** [comment]
Will continue with @charlesvien PR
